export const GET_ALL_COURSES = "GET_ALL_COURSES";
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST";
